### ISSUE TITLE
loopPieces in CPos doesnt seem to work properly... Theres a sigsev. To be examined

### ISSUE THREAD

**Issue by Wittmaxi** [MaximilianJugendForscht/baumhaus#15]

**Comment by Archimedyz** [comment]
I'll take a look into the issue.
I am able to resolve the problem by relacing the two calls to  "getPossibleMoves()" with a single call, and storing the value in a temporary variable. But I have to still locate the underlying issue, as the double call should not have lead to the seg fault.
